const axios = require('axios');
const { Octokit } = require('@octokit/rest');

// ============================================
// CONFIGURATION - Load from environment variables
// ============================================

const CLICKUP_API_KEY = process.env.CLICKUP_API_KEY;
const CLICKUP_SECRET = process.env.CLICKUP_SECRET;
const CLICKUP_BOT_USER_ID = parseInt(process.env.CLICKUP_BOT_USER_ID || '0');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_BASE_BRANCH = process.env.GITHUB_BASE_BRANCH || 'main';

const octokit = new Octokit({
  auth: GITHUB_TOKEN
});

// ============================================
// HELPER FUNCTIONS
// ============================================

async function getTaskDetails(taskId) {
  try {
    const response = await axios.get(`https://api.clickup.com/api/v2/task/${taskId}`, {
      headers: {
        'Authorization': CLICKUP_API_KEY,
        'Content-Type': 'application/json'
      }
    });

    return response.data;
  } catch (error) {
    console.error('Error fetching task details:', error.message);
    return null;
  }
}

async function processTask(task) {
  const taskId = task.id;
  const taskTitle = task.name;
  const taskDescription = task.description || '';

  console.log(`Processing task ${taskId}: ${taskTitle}`);

  // Mock Claude API - generate hardcoded file
  const generatedCode = `// Generated from ClickUp Task: ${taskTitle}
// Task ID: ${taskId}
// Description: ${taskDescription}

console.log("Hello World");

// This is a mocked file.
// TODO: Integrate Claude API to generate actual code based on the task.
`;

  const branchName = `task-${taskId}`;
  const fileName = 'generated-code.js';
  const commitMessage = `Add generated code for ClickUp task: ${taskTitle}`;
  const prTitle = `[ClickUp #${taskId}] ${taskTitle}`;
  const prBody = `## ClickUp Task

**Task ID:** ${taskId}
**Title:** ${taskTitle}
**Description:**
${taskDescription || 'No description provided'}

---

This PR was automatically generated by the ClickUp-Claude-GitHub integration.

Generated file: \`${fileName}\`
`;

  try {
    // Get base branch reference
    const { data: refData } = await octokit.git.getRef({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      ref: `heads/${GITHUB_BASE_BRANCH}`
    });

    const baseSha = refData.object.sha;
    console.log(`Base branch SHA: ${baseSha}`);

    // Create new branch
    await octokit.git.createRef({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    });

    console.log(`Created branch: ${branchName}`);

    // Create/update file
    const contentEncoded = Buffer.from(generatedCode).toString('base64');

    await octokit.repos.createOrUpdateFileContents({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      path: fileName,
      message: commitMessage,
      content: contentEncoded,
      branch: branchName
    });

    console.log(`Committed file: ${fileName}`);

    // Create Pull Request
    const { data: prData } = await octokit.pulls.create({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      title: prTitle,
      head: branchName,
      base: GITHUB_BASE_BRANCH,
      body: prBody
    });

    console.log(`Pull Request created: ${prData.html_url}`);

    return prData;

  } catch (error) {
    console.error('Error creating GitHub PR:', error.message);
    throw error;
  }
}

// ============================================
// SERVERLESS FUNCTION HANDLER
// ============================================

module.exports = async (req, res) => {
  try {
    // Enable CORS
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

    if (req.method === 'OPTIONS') {
      res.status(200).end();
      return;
    }

    if (req.method !== 'POST') {
      return res.status(405).json({ error: 'Method not allowed' });
    }

    console.log('Received ClickUp webhook event');

    const event = req.body;

    console.log('Task ID:', event.task_id);
    console.log('Event Type:', event.event);

    // Check if this is a task assignment event
    if (event.event === 'taskAssigneeUpdated' || event.event === 'taskCreated') {
      const task = event.task_id ? await getTaskDetails(event.task_id) : null;

      if (task) {
        console.log('Task Title:', task.name);
        console.log('Task Description:', task.description || '(no description)');

        // Check if task is assigned to bot user
        const assignees = task.assignees || [];
        const isBotAssigned = assignees.some(assignee => parseInt(assignee.id) === CLICKUP_BOT_USER_ID);

        if (isBotAssigned) {
          console.log('Task assigned to bot - processing...');

          await processTask(task);

          return res.status(200).json({
            success: true,
            message: 'Task processed and PR created'
          });
        }
      }
    }

    res.status(200).json({ success: true, message: 'Webhook received' });

  } catch (error) {
    console.error('Error processing webhook:', error);
    console.error('Stack trace:', error.stack);
    return res.status(500).json({
      error: error.message,
      stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
};
